---
title: "Drought manipulation manual measurements"
author: "George Xenakis"
date: "2023-03-27"
output: 
  html_document: 
    fig_caption: yes
  word_document: default
  pdf_document: 
    fig_caption: yes
    keep_tex: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      error = FALSE, 
                      message = FALSE, 
                      evaluate=TRUE,
                      results = 'hide')

knitr::opts_knit$set(kable.force.latex = FALSE)

```


```{r}

## The colour palette to use for some of the graphs
jet.colours <- colorRampPalette(c("#00007F", "blue", "#007FFF", "cyan", "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000"))
colours<-jet.colours(7)
colours12 <- jet.colours(12)

## ------------------------------------------------------------------------ ##
meanPerDate <- function(data,datesArray){
    start <- as.POSIXct(datesArray,tz="GMT")+lubridate::hours(8)
    end <- as.POSIXct(datesArray,tz="GMT")+lubridate::hours(16)
    l <- list()
    for(i in 1:length(datesArray)){
        l[[i]] <- data%>%filter(between(timestamp,start[[i]],end[[i]]))%>%
            group_by(timestamp=as.Date(timestamp))%>%
            summarise(across(1:10,.f=list(mean=mean,se=se.f)))
    }
    d <- do.call("rbind",l)
}

## ======================================================================== ##

## Set up some directory locations
dtclassDir <- "/home/george/Documents/DTCLASS/data/"

## Read all the necessary timeseries datasets
## biomet <- readRDS(file=paste0(dtclassDir,"processed/biomet/biomet.RDS"))
sapData <- readRDS(file=paste0(dtclassDir,"processed/sapflow/sapData.RDS"))
manual <- readFile("/home/george/Documents/DTCLASS/data/processed/manual_measurements/manual.csv",h=T)%>%mutate(id=ID)%>%separate(id,c("treatment","treeNo"))%>%rename("date"="Date")%>%mutate(treeNo=as.numeric(treeNo))


## Create a new dataframe with the treatment code and tree number
treatment <- tibble(treeID=c("C-6","C-8","C-12","MD-2","MD-5","MD-16"))%>%separate(treeID,c("treatment","treeNo"))%>%mutate(treeNo=as.numeric(treeNo))

manualDates <- manual%>%select(date)%>%as.data.frame()%>%pull("date")%>%unique()%>%as.character()

meanSFManualList <- lapply(sapData,meanPerDate,datesArray=manualDates)
meanSFManualData <- do.call("rbind",meanSFManualList)%>%
    select(timestamp,treeNo_mean,Vs_in_adj_mean,Vs_in_adj_se)%>%
    rename_with(.,~gsub("_mean","",.x,fixed=TRUE))%>%
    rename_with(.,~gsub("_adj","",.x,fixed=TRUE))%>%
    rename_with(.,~gsub("_in","",.x,fixed=TRUE))%>%
    rename_with(.,~gsub("_se",".se",.x,fixed=TRUE))%>%
    rename("date"="timestamp")%>%
    mutate(Vs=Vs*0.01*0.000277778,
           Vs.se=Vs.se*0.01*0.000277778)%>% ## 0.01 cm/h->m/h, 0.000277778 m/h->m/s or m3/m2/s
    left_join(treatment,by="treeNo")

manualData <- meanSFManualData%>%left_join(manual,by=c("date","treeNo","treatment"))%>%
    mutate(PsiL=PsiL*-0.1, ## bar to MPa
           deltaPsi=PsiL-PsiS,
           r=(deltaPsi/Vs)*1e-5
           )


```


## Manual measurements
<!-- First let's look at all the variables. -->

<!-- ```{r,fig.width=16,fig.height=10} -->
<!-- manual%>%mutate(date=Date)%>%unite(d.tr,c("date","treatment"),sep="-")%>% -->
<!--     gather(key="variable",value="value",4:7)%>% -->
<!--     ggplot(.)+plotAesthetic+ -->
<!--     geom_boxplot(aes(d.tr,value,group=d.tr))+ -->
<!--     facet_wrap(.~variable+Date,scales="free") -->
<!-- ``` -->


This is the mid-day needle cohort water potential

```{r}

labels <- c("First wet","First drought","Second wet","Second drought","Third wet")
names(labels) <- manualDates


manual%>%
    mutate(PsiL=PsiL*-0.1)%>%
    ggplot(data=.)+
    plotAesthetic+Theme+
    geom_boxplot(aes(treatment,PsiL,group=treatment,fill=treatment))+
    geom_hline(yintercept=0,linetype=2)+
    facet_grid(.~date,labeller=as_labeller(labels))+
    labs(x="Treatment",y=expression(Psi[C]~"[MPa]"))

```

Finally, let's look at the soil water potential.
```{r}
manual%>%
    mutate(PsiL=PsiL*-0.1)%>%
    ggplot(data=.)+
    plotAesthetic+Theme+
    geom_boxplot(aes(treatment,PsiS,group=treatment,fill=treatment))+
    geom_hline(yintercept=0,linetype=2)+
    facet_grid(.~date,labeller=as_labeller(labels))+
    labs(x="Treatment",y=expression(Psi[S]~"[MPa]"))

```